rism-digital/muscat

2- INSTALL.rdoc
The `-e` parameter needs a value for starting up MUSCAT, which was missing in the readme.
=> Install documentation fixes

public/images/logo-large-default.png
Adds a default large logo by using a symbolic link to the existing RISM-CH large logo.
=> Issue #633 - symbolic links to RISM logo as default large logo

Gemfile, config/marc/default/source/template_configuration.yml
Records of unspecified type assume a default value of 0:
https://github.com/rism-ch/muscat/blob/develop/db/schema.rb#L442
However, this value of 0 (https://github.com/rism-ch/muscat/blob/develop/lib/marc_source.rb) is not mapped in https://github.com/rism-ch/muscat/blob/develop/config/marc/default/source/template_configuration.yml#L60.  This patch provides a reasonable source default, so they can be edited without crashing Muscat.
=> Provide a fallback for unspecified record type

Gemfile, app/admin/catalogue.rb, app/admin/guidelines.rb, app/admin/holding.rb, app/admin/institution.rb, app/admin/person.rb, app/admin/source.rb, app/admin/work.rb, app/models/catalogue.rb, app/models/config_file_path.rb, app/models/holding.rb, app/models/institution.rb, app/models/person.rb, app/models/work.rb, housekeeping/correct/11_fix_catalogue_with_nil_marc.rb, housekeeping/correct/41_migrate_conv.rb, housekeeping/doc/generate_doc.rb, housekeeping/upgrade_3.6_a1/001_split_holding_records.rb, housekeeping/upgrade_ch/05_convert_ms_to_pr.rb, lib/editor_configuration.rb, lib/editor_validation.rb, lib/guidelines.rb, lib/marc.rb, lib/template.rb
There are uses RISM::MARC and RISM::EDITOR_CONFIGURATION all over Muscat, and if a value other than default is defined, the application fails in unsuspected places.
This patch creates a generic function so it falls back to default if a specific file does not exist. I have been using for a while in two different Muscat test instances, one having the default values and another having created a custom value.
=> Generalise fallback to default file

config/sample_application.rb
Most configuration values in config/application.rb (as copied from
config/sample_application.rb) have an explicit "default" value, except
for EDITOR_PROFILE, that may have an empty string. This complicates
the logic when this variable is used in Muscat, as it has to be
compared to empty string and then set to "default" before using it.
=> Require default EDITOR_PROFILE to be set as "default"

2- INSTALL.rdoc
Remove obsolete requirements and general documentation cleanup.  Document
Muscat installation on Debian 10 (Buster).
=> Documentation cleanup and update Debian 10 requisites

Gemfile
Using newer Thor versions (at least 1.0.x) create a name conflict of the
Command class (see https://github.com/erikhuda/thor/issues/721).  This is a
temporary workaround until a better solution is found.
=> Avoid TypeError: superclass mismatch for class Command error

config/editor_profiles/default/configurations/CatalogueLabels.yml, config/editor_profiles/default/configurations/HoldingBasicLabels.yml, config/editor_profiles/default/configurations/InstitutionLabels.yml, config/editor_profiles/default/configurations/PersonLabels.yml, config/editor_profiles/default/configurations/SourceLabels.yml, config/editor_profiles/default/configurations/WorkLabels.yml, config/locales/pl.yml
This is a replacement pull request to [pull#979](https://github.com/rism-ch/muscat/pull/979).
Polish translation added in files listed below: 
- `config/editor_profiles/default/configurations/CatalogueLabels.yml`
- `config/editor_profiles/default/configurations/HoldingBasicLabels.yml`
- `config/editor_profiles/default/configurations/InstitutionLabels.yml`
- `config/editor_profiles/default/configurations/PersonLabels.yml`
- `config/editor_profiles/default/configurations/SourceLabels.yml`
- `config/editor_profiles/default/configurations/WorkLabels.yml`
- `config/locales/pl.yml`
This pull request can be merged automatically with `muscat/polish-version` branch.
=> Polish translation added to polish-branch

2- INSTALL.rdoc
Apache-itk, or the Apache multiuser-module, is a great way to simplify the
administration of multiple Apache applications in a single server.  As each
Apache runs as each user, and as the users are owned by each Apache process,
there is no longer the need to change file ownership or running sudo.
Moreover, each Apache cannot read the other users files.
As Muscat runs flawlessly under Apache-itk, document this alternative.
=> Document the Apache-itk option

app/views/catalog/_previous_next_doc.html.erb
If bibliographic records other than Sources, like Catalogues, are made
accessible through the Blacklight interface, allow them to be edited like
sources, and link them to the right record type.
=> Allow edit other bibliographic records from Blacklight

lib/editor_configuration.rb, lib/editor_validation.rb
As RISM::EDITOR_PROFILE may no longer have an empty value, clean up the last
couple of obsolete traces where this condition was still taken into account.
=> Deprecate empty RISM::EDITOR_PROFILE

app/admin/catalogue.rb, app/views/admin/catalogues/select_new_template.html.erb, config/locales/en.yml, config/marc/default/catalogue/template_configuration.yml, lib/editor_configuration.rb
This patch is the first step towards having different templates for
secondary literature.  It synchronises some code and configuration files
from sources so now, when creating a new record, appears a menu with a
single choice, the legacy template.
There are yet no new fields (like record type) or tag changes.
=> Allow different templates for secondary literature

config/sample_application.rb
Make sample_application.rb friendlier to newcomers by documenting each
variable.  Reorder slightly some of them to put the most important first,
remove obsolete indentation, normalise spaces and quote signs, and make the
file utf-8 friendly.
=> Document sample_application.rb variables

config/environments/production.rb
This changes the default log level for production environments to WARN from DEBUG. This helps keep the file sizes of logs in production down.
=> Fixed: Default to warning in production

config/blacklight.yml
The Blacklight settings point to 'default' being the default core for Blacklight in production, but sunspot configures the default core to be 'production'. 
This PR aligns the two by changing the default setting for Blacklight to 'production'.
=> Fix default blacklight Solr settings

bin/muscat_execute_job, config/editor_profiles/default/configurations/CatalogueLabels.yml, config/editor_profiles/default/configurations/HoldingBasicLabels.yml, config/editor_profiles/default/configurations/InstitutionLabels.yml, config/editor_profiles/default/configurations/PersonLabels.yml, config/editor_profiles/default/configurations/SourceLabels.yml, config/editor_profiles/default/configurations/WorkLabels.yml, config/initializers/active_admin.rb, config/locales/marc_records/de.yml, config/locales/marc_records/en.yml, config/locales/marc_records/es.yml, config/locales/marc_records/fr.yml, config/locales/marc_records/it.yml, config/locales/marc_records/pl.yml, config/locales/marc_records/pt.yml, config/locales/pl.yml, config/locales/plurals.rb
This commit adds the new translations and editor configuration files for moving the translation mechanism to the standard Rails system.
Will require a small change to the translation loading system for the editor, which @xhero has tested on his side. 
Fixes #1004
=> New: Move to standard Rails translation mechanism

app/assets/config/manifest.js
Due to a change in sprockets 4, the asset precompiling pipeline no longer worked to compile assets in the Muscat app folder.
The fix was to add the paths in the app/assets/config/manifest.js. This is documented in the Sprockets upgrading documentation here: https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs
=> Fix asset compilation in 7.0.2

app/views/catalog/_previous_next_doc.html.erb
Record type is in singular (Source) not plural (Sources). Fixes #1057
=> Fix edit link for sources in faceted search

app/models/publication.rb
:wf_stage in Solr allows Muscat Blacklight interface search by publications
approved or not, so they can be restricted to public visibility, like
Sources.  Add it to paper_trail as well.  Reorder a few more lines to match
Sources.
=> Index :wf_stage in Publications like Source

lib/sru.rb
Currently (01/2020) the number of results for a wildcard query is
1191491, which exceeds the limit of 999999 and leads to a
info:srw/diagnostic/1/61 (first record out of range), which is a bit
irritating.
Example:
* https://muscat.rism.info/sru?maximumRecords=100&operation=searchRetrieve&query=*&recordSchema=marc&startRecord=1000026&version=1.1
=> increase allowed offset on SRU endpoint

housekeeping/make_manifest.rb
Some improvements to the manifest generation script for Muscat. Note that this hasn't actually been tested, since I don't have a working Muscat installation locally.
- Changes the path to the new RISM Digital IIIF server
- Fixes the canvas ID property to be a full URI
- Improves the 'related' property with a label and format per the spec recommendations
- Improves the human readable label of the canvas to an enumerated image value instead of the filename
- Updates the value written back to Muscat
=> Fixed: Improved output of the IIIF manifest script

lib/marc_person.rb
The MarcPerson class is used both for sources and publications.  The
composer and composer_d variables are certainly local, and this change is
mostly useless, except that it now matches the function name, clarifies its
use and helps contributors familiarisating with Muscat code that it generic,
not only for musical sources.
=> Change local variable name composer to full_name

db/migrate/20210514043225_add_index_to_publications.rb
Create the same indexes as in sources, as it is needed for fast date
searching.
Please note that I haven't attached the db/schema.rb file in this patch due
to a conflict and and I'm unsure how to proceed, but fortunately
db/schema.rb is (re)generated automatically after performing 'rails
db:migrate', so please do this step for me.  Thanks.
=> Create indexes for created_at and updated_at in publications

config/editor_profiles/default/configurations/HoldingBasicLabels.yml, config/editor_profiles/default/configurations/SourceLabels.yml, config/locales/marc_records/de.yml, config/locales/marc_records/en.yml, config/locales/marc_records/es.yml, config/locales/marc_records/fr.yml, config/locales/marc_records/it.yml, config/locales/marc_records/pl.yml, config/locales/marc_records/pt.yml
See rism-digital/translations#21 for details. This updates the local translation files for Muscat to bring them inline with the upstream changes, as well as updating the key for the places where it is used.
=> Update labels for co-composer

solr-configuration/muscat/solrconfig.xml
This commit adds the themax jar path to the Solr config. If it doesn't exist, Solr will just ignore it.
=> Fixed: Add Themax jar path

config/sample_application.rb
Configuring DIGITAL_OBJECT_PATH can be tricky due to the behaviour of Ruby on Rails relative and absolute paths.  This patch gives a working example, with hints, on how to create a working one, out of Muscat software directory tree, so it is not affected by changes on it.
Closes #1314
=> Improve DIGITAL_OBJECT_PATH documentation with an example

lib/marc_source.rb
Marc21 bibliographic level distinguishes between d (subunit) and m (monograph/item) that, in Muscat record types, correspond to edition_content (Printed music edition, item in collection) and edition (Printed music edition, collection parent record or individual item).
https://www.loc.gov/marc/bibliographic/bdleader.html
Split the logic between both types instead of putting all together as edition_content.
Closes #1318
=> Recognize subunit as different from monograph in sources leader

app/assets/javascripts/marc_editor_validation.js
As the names of data-scroll-target editor validation target is taken from the translated texts, when there is an apostrophe (') the javascript parser cannot know where the name ends.  Use a double quote to enclose the element.
Closes #1360
=> Escape data-scroll-target editor validation javascript element

app/views/marc_show/_show_dnb_link.html.erb
The URL prefix for BnF identifiers was missing the initial "cb".
=> Fix link to BNF catalogue

app/controllers/catalog_controller.rb, config/locales/ca.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pl.yml, config/locales/pt.yml
There are still obsolete references to "catalogues" before being renamed to "publications", this time in the filter strings.
Part of #1028
=> Rename obsolete catalogues filter text to publications

app/admin/user.rb
Closes #1391.  Massive deletion of users is still allowed, as it is not clear that this ability should be removed.
Thanks to @ivan-mr from @CodiTramuntana for finding the trivial but not obvious way of fixing it.
=> Do not allow the creation of folders of users

app/admin/folder.rb
Make sure that the current filter for "contains" does a substring search, not a full name search, and create a filter by owner and another for folder type.
Closes #1389
Thanks to @ivan-mr from @CodiTramuntana for his help with procs and collections.
=> Fix current folder filter behaviour and create a couple more

config/sru/service.config.yml
since we have some "lib_siglum_order" and "siglum_order" confusion in the index config, this one brings back the old one to enable sru sigla search again. It's really only a hot fix
=> Fix sru sigla search

config/locales/ca.yml, config/locales/en.yml, config/locales/es.yml, config/locales/pl.yml, config/locales/pt.yml
Deleted records did not have a translation acronym, and some newer translation files do have translations for status codes, although they are not used.  Remove them.
Fixes #1441
=> Add DEL acronym for deleted records, unify translation files

vendor/assets/stylesheets/muscat.scss
Muscat remembers search filters until they are explicity cleared, and that confuses users because the list of records doesn't match with what is expected.  Move the the information box to the top of the sidebar so it is obvious that there are filters active.
Thanks to @ivan-mr from @CodiTramuntana for finding a css-only solution.
Closes #1251
=> Move current filter information at top of sidebar

app/admin/digital_object.rb, app/admin/institution.rb, app/admin/liturgical_feast.rb, app/admin/person.rb, app/admin/place.rb, app/admin/publication.rb, app/admin/source.rb, app/admin/standard_term.rb, app/admin/standard_title.rb, app/admin/work.rb, app/admin/work_node.rb, app/helpers/section_sidebar_folder_actions_helper.rb, app/models/institution.rb, app/views/activeadmin/_section_sidebar_folder_actions.html.erb, config/locales/ca.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pl.yml, config/locales/pt.yml, lib/folder_controller_actions.rb
Currently the only way to add items to folders is via a batch selection form a list created in the list view.  This patch allows to add and remove them from the full record view.  Closes #931.
This second version unifies in a single (and hopefully complete) commit and replaces #1388.
Thanks to @ivan-mr from @CodiTramuntana for his help finding a way of doing it following the Rails conventions.
=> Allow items to be added and removed from folders, v2

lib/editor_configuration.rb
When cataloging Marc records, the Marc tag number is shown (ex: 100), but not the subfield (ex: $a).  This information is useful to understand which value has to be filled in, and to find documentation and/or examples.
This patch adds it between parenthesis after its name, like the tag.
=> Display subfield in Marc editor

config/editor_profiles/default/configurations/PublicationLabels.yml
We had a field in Kallisto to record dates of publication for a journal (to clarify: beginning and end dates of a serial publication). This is in Muscat as 520 but is labeled `Contents note`. This correction renames the field to `Dates of publication` (following the new key added in https://github.com/rism-digital/translations/pull/124).
=> Renaming 520 in Secondary Literature

app/views/admin/users/_help_text.ca.md, app/views/admin/users/_help_text.es.md
Without those files, it is not possible to edit user alerts if locale is set to Catalan or Spanish, as the application fails due to a missing help file.
=> Add missing user help files for Catalan and Spanish

config/sample_application.rb, lib/generators/muscat/install_saml_generator.rb, lib/generators/muscat/templates/devise_saml_authenticatable.rb, lib/generators/muscat/templates/saml_sessions_controller_override.rb
New Rails 7 loader (zeitwerk) conflicts with previous setup, and it does not load the libraries in the order they used to.  Change it slightly, and add an override rule in config/sample_application.rb
All the hard work, and thus, the merit, goes to @ivan-mr from @CodiTramuntana.
=> Update Muscat saml SSO authentication to Rails 7

db/migrate/20240521090418_add_display_name_to_people.rb, db/schema.rb
The commit 3ff0f26f6f5f161a764802dfc00a2e33c7f7c1ea removed full_name_d, that we have been using to create a richer display form of people (with life dates and other subfields that disambiguate similar names) for lists and autocompletions.  As requested by @xhero, this patch creates a new column named display_name for this purpose.  Its value will be generated in lib/marc_person.rb, with the goal to be generated only once, as it is used quite often, and generate it every time is costly.  I'm leaving this part for a future PR, as I need to make our usage compatible with upstream Muscat.
=> Add display_name to people

config/editor_profiles/default/configurations/InstitutionFormOptions.yml
Since we now have a Saudi Arabian institution with a siglum, we should probably also have this as a selectable country code
=> Add Saudi Arabia to Institution Country Codes list

app/admin/institution.rb, app/admin/person.rb, app/admin/publication.rb, app/admin/source.rb, app/admin/work_node.rb, app/controllers/sru_controller.rb, app/views/marc/_show_raw.html.erb, app/views/sru/_result.xml.erb, lib/marc.rb, lib/marc_gnd_work.rb, lib/marc_institution.rb, lib/marc_person.rb, lib/marc_source.rb, lib/marc_work.rb, lib/marc_work_node.rb
* Adds a `created_at` parameter to the calling functions
* Remove duplicating code
* Change `#` to `|` following marc specifications
```
=001 41010233
=003 DE-633
=005 20190303095544.0
=008 180108||||||||||||||||||||||||||||||||||
=040 ##$aDE-633$bger$cDE-633
=042 ##$anot individualized
=100 1#$aAachen church copyist 1$d19.sc
=375 ##$aunknown
=550 ##$aCopyist 
```
=> Adds 008 to the marc export

app/views/editor/_record_actions.html.erb
Record action text was only in English, so add the i18n wrapper.  Add also the deprecated and deleted statuses, if they are also useful at RISM; otherwise, just drop both lines.
=> Add i18n to record actions pulldown texts

housekeeping/export/xml-export.rb
* Exports sources by default unless a model name is passed as first parameter (e.g., `Person`)
* Exports to `./export.xml` unless an output file is specified as second parameter
=> Simple export script to export to MarcXML

config/environments/development.rb
Since Rails 6 (August 2019), it is considered that it is no longer necessary to check for obsolete browsers, so remove it also from Muscat.  This creates shorter and cleaner urls.  See
https://guides.rubyonrails.org/6_0_release_notes.html#action-view-notable-changes
=> Remove obsolete utf8=✓ from url parameters

housekeeping/export/xml-export.rb
* Change to options (`-m` for the model and `-f` for the filename)
* Add `-l` for legacy deprecated ids
=> Adjust script to produce export files with deprecated ids

app/admin/place.rb
Of all non-marc authority records, place is the only that doesn't display wf_stage, although the field exists in the database.  Make it visible, so it is homogeneous with the others.
Part of #1584
=> Display wf_stage in place authority records

app/admin/liturgical_feast.rb, app/admin/place.rb, app/admin/standard_term.rb, app/admin/standard_title.rb
Currently, after editing those records, Muscat takes you to the record list, without allowing to double-check if the editing was right.
Partially closes #1584
=> After modifying non-marc authority files, show modified record
