config/locales/en.yml, config/locales/es.yml
=> I18n spanish

config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml
Localisations added for English, German, French and Italian as these localisations already have an entry for full_level I18n element.
=> Adds localisations for basic_level I18n element

app/admin/folder.rb, app/models/ability.rb, app/models/folder.rb, app/models/user.rb
this one are adding the publish action to users(catalogers) for folders if explicitly **all records** are in his workgroup-domain. Also a "published" column is added to the index page
=> 5.1 devel folders

app/models/liturgical_feast.rb, app/models/person.rb, app/models/work.rb, app/views/works/_show_related_feast.html.erb, app/views/works/_show_related_person.html.erb, app/views/works/_show_work_link.html.erb, config/editor_profiles/default/configurations/WorkFormOptions.yml, config/editor_profiles/default/configurations/WorkLabels.yml, config/editor_profiles/default/configurations/WorkLayoutDefault.yml, config/editor_profiles/default/configurations/WorkLayoutShow.yml, config/marc/tag_config_work.yml, db/migrate/20190103152222_add_work_feast.rb, db/migrate/20190103152222_add_work_relation.rb, db/schema.rb
this one add some new relations to the work model, including a **new migration**
=> 5.1 devel works

3- IMPORT.rdoc
Fix some obsolete rails runner syntax
=> Update 3- IMPORT.rdoc

2- INSTALL.rdoc
Apache 2.2 reached end-of-life last year. Update docs accordingly.
=> Update Apache configuration to 2.4

app/admin/source.rb, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/sunspot.yml, lib/template.rb, lib/template_controller_actions.rb, vendor/assets/stylesheets/muscat.scss
same as https://github.com/rism-ch/muscat/pull/859
=> 5.3 devel templatechange

app/models/ability.rb, db/seeds.rb
same as https://github.com/rism-ch/muscat/pull/852
=> Added role junior_editor

app/admin/catalogue.rb
Catalogue record type shares with Source that both are bibliographic Marc
records.  In Muscat, Source is more complete and has more options, like the
ability to choose different templates.  This patch does not add or modifies
anything at all.  It just reorders the lines of code of catalogue.rb so that
the common ones are aligned with source.db and is easier to spot the
differences.
=> Reorder catalogue.rb code like source.rb

config/editor_profiles/default/configurations/SourceLabels.yml
=> Fixed: conflicting language keys in SourceLabels

config/editor_profiles/default/configurations/SourceLabels.yml
Otherwise they evaluate to False
Fixes #1011
=> Fixed: Quote 'No' values

housekeeping/make_manifest.rb
This back-ports updates to the IIIF manifest generator.
=> WIP: Manifest generator

app/controllers/application_controller.rb, config/sample_application.rb, spec/features/anonymous_navigation_spec.rb
This PR is to avoid having to hack the application in order to allow anonymous users to browse the site.
Related to #787
=> Add configuration to enable anonymous users to browse the site

app/models/publication.rb, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pl.yml, config/locales/pt.yml, db/migrate/20211119103904_rename_revue_title_to_journal.rb, lib/marc_import.rb, lib/marc_publication.rb, spec/support/factories/publication.rb
=> Rename revue_title to journal in Publications

app/models/person.rb, db/migrate/20211213070144_remove_comments_from_people.rb, lib/marc_person.rb
=> Remove comments attribute from Person model and db

app/views/catalog_download/confirm.html.erb
Fixes a typo in the e-mail message notification
=> Update e-mail message

config/sru/service.config.yml
same as previous pr, but without schema.rb
=> Changing index field name

config/locales/en.yml
=> Fixed: Siglum misspelling

config/editor_profiles/default/configurations/SourceFormOptions.yml
See https://github.com/rism-digital/muscat/issues/1227
=> Remove "Composite" from the values in 593 $b

db/seeds.rb
Username cannot be empty.  Fixes #1302
=> Fill in username in seed values

app/admin/work.rb, lib/marc_work.rb
Based on similar implementations
=> Add support for duplicating a work

config/sru/service.config.yml
=> Updated sru index

config/editor_profiles/default/configurations/PersonFormOptions.yml, config/editor_profiles/default/configurations/PersonLabels.yml
Added philipinnes to selection of 041 with people, s. comment in https://muscat.rism.info/admin/people/51015794
=> Added philipinnes to people countries

config/sru/service.config.yml
rest of remaining to lib_siglum
=> Fix old sru configuration

config/i18n-js.yml
=> Add Catalan locale to the list of js languages

app/views/sru/_explain.xml.erb, config/sru/service.config.yml, spec/controllers/sru_spec.rb
The hostname was incorrect in the SRU interface
=> Change host in SRU

config/locales/ca.yml, config/locales/es.yml
=> Improvements to Catalan and Spanish translations

app/jobs/export_records_job.rb
Fix the namesapce in the MarcXML export. There are still wrong additional XML processing instruction between each record in the export
=> Fix the xml marc root in export

lib/marc_import.rb
Without commiting the index, indexing is lost.  After months without understanding why it didn't work, now I see it, yes.
=> If set to index when importing records, tell Solr to commit them

config/editor_profiles/default/configurations/shared/SharedLanguageLabels.yml
I think this was an errant addition.
=> Remove country code from language file

app/views/editor/_record_actions.html.erb
It was my fault, a typo in 0231d2ef27a3becf343ff2e988eae662ea6f571e
=> Remove spurious percent char

app/admin/work_node.rb, app/views/admin/work_nodes/_work_nodes_help_show.en.md, app/views/admin/work_nodes/_work_nodes_help_show.fr.md
* To be reviewed and translated
=> Add initial work node help (en and fr)

app/admin/liturgical_feast.rb, app/admin/place.rb, app/admin/standard_term.rb, app/admin/standard_title.rb
Those records already had an owner, but it was not visible on the screen.
Fixes #1584
=> Display record owner for all non-marc authority files
